name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run tests with Ginkgo
        run: |
          go install github.com/onsi/ginkgo/ginkgo@latest
          ginkgo -r
        env:
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_PEM_NO_PASS: ${{ secrets.SSH_PEM_NO_PASS }}
          SSH_PEM_WITH_PASS: ${{ secrets.SSH_PEM_WITH_PASS }}
          BOT_PEM: ${{ secrets.BOT_PEM }}
          BOT_INSTALLATION_ID: ${{ secrets.BOT_INSTALLATION_ID }}
          BOT_ID:  ${{ secrets.BOT_ID }}